/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface TR0001NetSaleDetail {
  acc_no: string | null;
  acc_type: number | null;
  agt_id: number | null;
  agt_short_name: string | null;
  agt_sub_type_code: string | null;
  box_number: string | null;
  brb_qty: number | null;
  brt_qty: number | null;
  bst_qty: number | null;
  bxt_qty: number | null;
  dd_vch: number | null;
  ddf_qty: number | null;
  ddn_qty: number | null;
  dir_qty: number | null;
  dist_dt: Date | null;
  ed_code: string | null;
  ext_qty: number | null;
  fre_qty: number | null;
  link_type: number | null;
  pub_code: string | null;
  rec_create: Generated<Date | null>;
  ret_qty: number | null;
  row_id: Generated<number>;
  sto_qty: number | null;
  uar_qty: number | null;
  user_code: string;
  user_tran_id: number;
  vch_qty: number | null;
  w_agt_id: number | null;
}

export interface TUser {
  accum_logon_time: Generated<Date | null>;
  code: string;
  count_reset_date: Date | null;
  description: string | null;
  email_address: string | null;
  employee_id: number | null;
  expiry_dt: Date | null;
  forename: string | null;
  last_logoff_dt: Date | null;
  last_logon_dt: Date | null;
  login_alias: string | null;
  login_count: number | null;
  login_day_pattern: string | null;
  login_name: string;
  login_time_end: number | null;
  login_time_start: number | null;
  mob_std_code: string | null;
  mob_tel_no: string | null;
  named_user: number | null;
  password: string | null;
  permissions: string | null;
  permissions_2: string | null;
  permissions_3: string | null;
  pw_expiry_dt: Date | null;
  rec_create: Generated<Date | null>;
  rec_modify: Generated<Date | null>;
  region_check: number;
  surname: string | null;
  suspended: Generated<number>;
  title: string | null;
  use_alias: number;
  use_expiry_dt: number;
  use_pw_expiry_dt: number;
  use_timeout_logoff: number;
  user_create: string | null;
  user_modify: string | null;
}

export interface DB {
  t_r0001_net_sale_detail: TR0001NetSaleDetail;
  t_user: TUser;
}
