/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface TUser {
  accum_logon_time: Generated<Date | null>;
  code: string;
  count_reset_date: Date | null;
  description: string | null;
  email_address: string | null;
  employee_id: number | null;
  expiry_dt: Date | null;
  forename: string | null;
  last_logoff_dt: Date | null;
  last_logon_dt: Date | null;
  login_alias: string | null;
  login_count: number | null;
  login_day_pattern: string | null;
  login_name: string;
  login_time_end: number | null;
  login_time_start: number | null;
  mob_std_code: string | null;
  mob_tel_no: string | null;
  named_user: number | null;
  password: string | null;
  permissions: string | null;
  permissions_2: string | null;
  permissions_3: string | null;
  pw_expiry_dt: Date | null;
  rec_create: Generated<Date | null>;
  rec_modify: Generated<Date | null>;
  region_check: number;
  surname: string | null;
  suspended: Generated<number>;
  title: string | null;
  use_alias: number;
  use_expiry_dt: number;
  use_pw_expiry_dt: number;
  use_timeout_logoff: number;
  user_create: string | null;
  user_modify: string | null;
}

export interface DB {
  t_user: TUser;
}
